apiVersion: flowcontrol.apiserver.k8s.io/v1beta2
kind: PriorityLevelConfiguration
metadata:
  annotations:
    apf.kubernetes.io/autoupdate-spec: "true"
  creationTimestamp: "2023-11-21T12:47:14Z"
  name: leader-election
spec:
  limited:
    assuredConcurrencyShares: 10
    lendablePercent: 0
    limitResponse:
      queuing:
        handSize: 4
        queueLengthLimit: 50
        queues: 16
      type: Queue
  type: Limited
status: {}
