apiVersion: v1
data:
  Answer: rohitohit.sr
  Question: What is the name of Ironman ?
kind: ConfigMap
metadata:
  creationTimestamp: "2023-10-05T08:16:11Z"
  name: example-quiz-configmap
  namespace: default
  ownerReferences:
  - apiVersion: juniper.juniper.com/v1
    blockOwnerDeletion: true
    controller: true
    kind: QuizQuestion
    name: example-quiz
    uid: 65b817c8-dc20-41ae-b021-79c4c2bf7711
