apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "2"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"labels":{"app":"example-webhook"},"name":"example-webhook","namespace":"default"},"spec":{"replicas":1,"selector":{"matchLabels":{"app":"example-webhook"}},"template":{"metadata":{"labels":{"app":"example-webhook"}},"spec":{"containers":[{"image":"trohit7/muatatewebhook:v25","name":"server","ports":[{"containerPort":8443,"name":"tls"},{"containerPort":80,"name":"metrics"}],"volumeMounts":[{"mountPath":"/etc/webhook/certs/","name":"webhook-tls-certs","readOnly":true}]}],"nodeSelector":{"kubernetes.io/os":"linux"},"securityContext":{"runAsNonRoot":true,"runAsUser":1234},"serviceAccountName":"example-webhook","volumes":[{"name":"webhook-tls-certs","secret":{"secretName":"example-webhook-tls"}}]}}}}
  creationTimestamp: "2023-12-11T11:45:45Z"
  labels:
    app: example-webhook
  name: example-webhook
  namespace: default
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: example-webhook
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: example-webhook
    spec:
      containers:
      - image: trohit7/muatatewebhook:v25
        imagePullPolicy: IfNotPresent
        name: server
        ports:
        - containerPort: 8443
          name: tls
          protocol: TCP
        - containerPort: 80
          name: metrics
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /etc/webhook/certs/
          name: webhook-tls-certs
          readOnly: true
      dnsPolicy: ClusterFirst
      nodeSelector:
        kubernetes.io/os: linux
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext:
        runAsNonRoot: true
        runAsUser: 1234
      serviceAccount: example-webhook
      serviceAccountName: example-webhook
      terminationGracePeriodSeconds: 30
      volumes:
      - name: webhook-tls-certs
        secret:
          defaultMode: 420
          secretName: example-webhook-tls
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2023-12-11T11:45:45Z"
    lastUpdateTime: "2023-12-21T13:49:17Z"
    message: ReplicaSet "example-webhook-685dd8c794" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  - lastTransitionTime: "2024-01-05T10:11:18Z"
    lastUpdateTime: "2024-01-05T10:11:18Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  observedGeneration: 2
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
