apiVersion: events.k8s.io/v1
deprecatedCount: 1
deprecatedFirstTimestamp: "2023-11-02T05:02:32Z"
deprecatedLastTimestamp: "2023-11-02T05:02:32Z"
deprecatedSource:
  component: kubelet
  host: minikube
eventTime: null
kind: Event
metadata:
  creationTimestamp: "2023-11-02T05:02:32Z"
  name: updatedquizapp-deployment1-7488ddc955-cxz9n.1793b5c76df91ef5
  namespace: default
note: Container image "trohit7/updatedquiz3:test3" already present on machine
reason: Pulled
regarding:
  apiVersion: v1
  fieldPath: spec.containers{updatedquizapp1}
  kind: Pod
  name: updatedquizapp-deployment1-7488ddc955-cxz9n
  namespace: default
  resourceVersion: "373186"
  uid: 2f375fd4-0ff7-4827-a1d9-da3797d25551
type: Normal
