apiVersion: v1
count: 1
eventTime: null
firstTimestamp: "2023-11-02T05:02:33Z"
involvedObject:
  apiVersion: v1
  fieldPath: spec.containers{updatedquizapp4}
  kind: Pod
  name: updatedquizapp-deployment4-746d9b5887-56q9w
  namespace: default
  resourceVersion: "373176"
  uid: ff921015-4cb4-411b-9c00-5e61651599de
kind: Event
lastTimestamp: "2023-11-02T05:02:33Z"
message: Started container updatedquizapp4
metadata:
  creationTimestamp: "2023-11-02T05:02:33Z"
  name: updatedquizapp-deployment4-746d9b5887-56q9w.1793b5c7c08cfd24
  namespace: default
reason: Started
reportingComponent: ""
reportingInstance: ""
source:
  component: kubelet
  host: minikube
type: Normal
