apiVersion: events.k8s.io/v1
deprecatedCount: 1
deprecatedFirstTimestamp: "2023-11-02T05:02:33Z"
deprecatedLastTimestamp: "2023-11-02T05:02:33Z"
deprecatedSource:
  component: kubelet
  host: minikube
eventTime: null
kind: Event
metadata:
  creationTimestamp: "2023-11-02T05:02:33Z"
  name: updatedquizapp-deployment4-746d9b5887-56q9w.1793b5c78b703720
  namespace: default
note: Created container updatedquizapp4
reason: Created
regarding:
  apiVersion: v1
  fieldPath: spec.containers{updatedquizapp4}
  kind: Pod
  name: updatedquizapp-deployment4-746d9b5887-56q9w
  namespace: default
  resourceVersion: "373176"
  uid: ff921015-4cb4-411b-9c00-5e61651599de
type: Normal
