apiVersion: events.k8s.io/v1
deprecatedCount: 4
deprecatedFirstTimestamp: "2023-10-30T14:51:41Z"
deprecatedLastTimestamp: "2023-10-31T12:39:32Z"
deprecatedSource:
  component: node-controller
eventTime: null
kind: Event
metadata:
  creationTimestamp: "2023-10-31T12:39:32Z"
  name: updatedquizapp-deployment4-746d9b5887-56q9w.1792ea3006c8428b
  namespace: default
note: Node is not ready
reason: NodeNotReady
regarding:
  apiVersion: v1
  kind: Pod
  name: updatedquizapp-deployment4-746d9b5887-56q9w
  namespace: default
  resourceVersion: "368969"
  uid: ff921015-4cb4-411b-9c00-5e61651599de
type: Warning
