apiVersion: apps/v1
kind: ReplicaSet
metadata:
  annotations:
    deployment.kubernetes.io/desired-replicas: "2"
    deployment.kubernetes.io/max-replicas: "3"
    deployment.kubernetes.io/revision: "2"
  creationTimestamp: "2023-09-29T06:39:15Z"
  labels:
    app: quizapp
    pod-template-hash: 567b8b576d
  name: quizapp-deployment-567b8b576d
  namespace: default
  ownerReferences:
  - apiVersion: apps/v1
    blockOwnerDeletion: true
    controller: true
    kind: Deployment
    name: quizapp-deployment
    uid: 8561e09b-7179-44a2-9cf5-9fc5528e0c73
spec:
  replicas: 2
  selector:
    matchLabels:
      app: quizapp
      pod-template-hash: 567b8b576d
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: quizapp
        pod-template-hash: 567b8b576d
    spec:
      containers:
      - command:
        - /bin/bash
        image: trohit7/quizapp:mytagcl
        imagePullPolicy: IfNotPresent
        name: quizapp
        ports:
        - containerPort: 80
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        tty: true
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
